name: flutter_iconly
description: 300+ Free icons for your next project in 5 styles (Light, Bold, Broken) for flutter. Icons designed by piqo.
version: 1.0.1
repository: https://github.com/m-noer/flutter_iconly.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: IconlyBold
      fonts:
        - asset: fonts/iconly_bold.ttf
    - family: IconlyLight
      fonts:
        - asset: fonts/IconlyLight.ttf
    - family: IconlyBroken
      fonts:
        - asset: fonts/IconlyBroken.ttf
